/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Robot02glb.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 0.12, 0]} rotation={[0.07, 0, Math.PI / 2]} scale={0.1}>
        <mesh geometry={nodes.pCube1.geometry} material={materials.Black} />
        <mesh geometry={nodes.pCube10.geometry} material={materials['RobotHEad:blinn1']} />
        <mesh geometry={nodes.pCube11.geometry} material={materials['RobotHEad:blinn1']} />
        <mesh geometry={nodes.pCube12.geometry} material={materials['RobotHEad:blinn1']} />
        <mesh geometry={nodes.pCube13.geometry} material={materials['RobotHEad:blinn1']} />
        <mesh geometry={nodes.pCube14.geometry} material={materials['RobotHEad:blinn1']} />
        <mesh geometry={nodes.pCube15.geometry} material={materials['RobotHEad:blinn1']} />
        <mesh geometry={nodes.pCube16.geometry} material={materials['RobotHEad:blinn1']} />
        <mesh geometry={nodes.pCube17.geometry} material={materials['RobotHEad:blinn1']} />
        <mesh geometry={nodes.pCube18.geometry} material={materials['RobotHEad:blinn1']} />
        <mesh geometry={nodes.pCube19.geometry} material={materials.Black} />
        <mesh geometry={nodes.pCube20.geometry} material={materials['RobotHEad:blinn1']} />
        <mesh geometry={nodes.pCube21.geometry} material={materials['RobotHEad:blinn1']} />
        <mesh geometry={nodes.pCube22.geometry} material={materials['RobotHEad:blinn1']} />
        <mesh geometry={nodes.pCube23.geometry} material={materials['RobotHEad:blinn1']} />
        <mesh geometry={nodes.pCube24.geometry} material={materials['RobotHEad:blinn1']} />
        <mesh geometry={nodes.pCube25.geometry} material={materials['RobotHEad:blinn1']} />
        <mesh geometry={nodes.pCube26.geometry} material={materials['RobotHEad:blinn1']} />
        <mesh geometry={nodes.pCube27.geometry} material={materials['RobotHEad:blinn1']} />
        <mesh geometry={nodes.pCube28.geometry} material={materials['RobotHEad:blinn1']} />
        <mesh geometry={nodes.Mesh058.geometry} material={materials.Body01} />
        <mesh geometry={nodes.Mesh058_1.geometry} material={materials['RobotHEad:blinn1']} />
        <mesh geometry={nodes.pCube30.geometry} material={materials['RobotHEad:blinn1']} />
        <mesh geometry={nodes.pCube31.geometry} material={materials['RobotHEad:blinn1']} />
        <mesh geometry={nodes.pCube32.geometry} material={materials['RobotHEad:blinn1']} />
        <mesh geometry={nodes.Mesh024.geometry} material={materials.Body01} />
        <mesh geometry={nodes.Mesh024_1.geometry} material={materials['RobotHEad:blinn1']} />
        <mesh geometry={nodes.pCube5.geometry} material={materials['RobotHEad:blinn1']} />
        <mesh geometry={nodes.pCube8.geometry} material={materials['RobotHEad:blinn1']} />
        <mesh geometry={nodes.pCube9.geometry} material={materials['RobotHEad:blinn1']} />
        <mesh geometry={nodes.Mesh102.geometry} material={materials.Body01} />
        <mesh geometry={nodes.Mesh102_1.geometry} material={materials['RobotHEad:blinn1']} />
        <mesh geometry={nodes.Mesh100.geometry} material={materials.Body01} />
        <mesh geometry={nodes.Mesh100_1.geometry} material={materials['RobotHEad:blinn1']} />
        <mesh geometry={nodes.polySurface35.geometry} material={materials.Black} />
        <mesh geometry={nodes.Mesh098.geometry} material={materials.Body01} />
        <mesh geometry={nodes.Mesh098_1.geometry} material={materials['RobotHEad:blinn1']} />
        <mesh geometry={nodes.polySurface37.geometry} material={materials.Body01} />
        <mesh geometry={nodes.polySurface38.geometry} material={materials.Black} />
        <mesh geometry={nodes.polySurface39.geometry} material={materials.Black} />
        <mesh geometry={nodes.Mesh089.geometry} material={materials.Body01} />
        <mesh geometry={nodes.Mesh089_1.geometry} material={materials['RobotHEad:blinn1']} />
        <mesh geometry={nodes.Mesh093.geometry} material={materials.Body01} />
        <mesh geometry={nodes.Mesh093_1.geometry} material={materials['RobotHEad:blinn1']} />
        <mesh geometry={nodes.polySurface54.geometry} material={materials.Black} />
        <mesh geometry={nodes.Mesh031.geometry} material={materials.Body01} />
        <mesh geometry={nodes.Mesh031_1.geometry} material={materials['RobotHEad:blinn1']} />
        <mesh geometry={nodes.Mesh027.geometry} material={materials.Body01} />
        <mesh geometry={nodes.Mesh027_1.geometry} material={materials['RobotHEad:blinn1']} />
        <mesh geometry={nodes.polySurface61.geometry} material={materials.Black} />
        <mesh geometry={nodes.Mesh065.geometry} material={materials.Body01} />
        <mesh geometry={nodes.Mesh065_1.geometry} material={materials['RobotHEad:blinn1']} />
        <mesh geometry={nodes.polySurface63.geometry} material={materials.Black} />
        <mesh geometry={nodes.Mesh061.geometry} material={materials.Body01} />
        <mesh geometry={nodes.Mesh061_1.geometry} material={materials['RobotHEad:blinn1']} />
        <mesh geometry={nodes.Mesh067.geometry} material={materials.Body01} />
        <mesh geometry={nodes.Mesh067_1.geometry} material={materials['RobotHEad:blinn1']} />
        <mesh geometry={nodes.Mesh063.geometry} material={materials.Body01} />
        <mesh geometry={nodes.Mesh063_1.geometry} material={materials['RobotHEad:blinn1']} />
        <mesh geometry={nodes.polySurface67.geometry} material={materials.Black} />
        <mesh geometry={nodes.Mesh033.geometry} material={materials.Body01} />
        <mesh geometry={nodes.Mesh033_1.geometry} material={materials['RobotHEad:blinn1']} />
        <mesh geometry={nodes.Mesh029.geometry} material={materials.Body01} />
        <mesh geometry={nodes.Mesh029_1.geometry} material={materials['RobotHEad:blinn1']} />
        <mesh geometry={nodes.polySurface70.geometry} material={materials.Black} />
        <mesh geometry={nodes.Mesh087.geometry} material={materials.Body01} />
        <mesh geometry={nodes.Mesh087_1.geometry} material={materials['RobotHEad:blinn1']} />
        <mesh geometry={nodes.polySurface72.geometry} material={materials.Black} />
        <mesh geometry={nodes.Mesh086.geometry} material={materials.Body01} />
        <mesh geometry={nodes.Mesh086_1.geometry} material={materials['RobotHEad:blinn1']} />
        <mesh geometry={nodes.polySurface74.geometry} material={materials.Body01} />
        <mesh geometry={nodes.polySurface76.geometry} material={materials.Black} />
        <mesh geometry={nodes.Mesh080.geometry} material={materials.Body01} />
        <mesh geometry={nodes.Mesh080_1.geometry} material={materials['RobotHEad:blinn1']} />
        <mesh geometry={nodes.polySurface79.geometry} material={materials.Black} />
        <mesh geometry={nodes.Mesh076.geometry} material={materials.Body01} />
        <mesh geometry={nodes.Mesh076_1.geometry} material={materials['RobotHEad:blinn1']} />
        <mesh geometry={nodes.polySurface81.geometry} material={materials.Black} />
        <mesh geometry={nodes.Mesh073.geometry} material={materials.Body01} />
        <mesh geometry={nodes.Mesh073_1.geometry} material={materials['RobotHEad:blinn1']} />
        <mesh geometry={nodes.polySurface86.geometry} material={materials.Black} />
        <mesh geometry={nodes.polySurface87.geometry} material={materials.Black} />
        <mesh geometry={nodes.polySurface88.geometry} material={materials.Black} />
        <mesh geometry={nodes.Mesh071.geometry} material={materials.Body01} />
        <mesh geometry={nodes.Mesh071_1.geometry} material={materials['RobotHEad:blinn1']} />
        <mesh geometry={nodes.polySurface90.geometry} material={materials.Black} />
        <mesh geometry={nodes.polySurface91.geometry} material={materials['RobotHEad:blinn1']} />
        <mesh geometry={nodes.polySurface92.geometry} material={materials['RobotHEad:blinn1']} />
        <mesh geometry={nodes.polySurface93.geometry} material={materials['RobotHEad:blinn1']} />
        <mesh geometry={nodes.polySurface94.geometry} material={materials['RobotHEad:blinn1']} />
        <mesh geometry={nodes.polySurface95.geometry} material={materials.Default_Material} />
        <mesh geometry={nodes.polySurface96.geometry} material={materials.Body01} />
        <mesh geometry={nodes.polySurface97.geometry} material={materials.Body01} />
        <mesh geometry={nodes.polySurface98.geometry} material={materials.Default_Material} />
        <mesh geometry={nodes.Mesh060.geometry} material={materials.Body01} />
        <mesh geometry={nodes.Mesh060_1.geometry} material={materials['RobotHEad:blinn1']} />
        <mesh geometry={nodes.pSphere12.geometry} material={materials.Black} />
        <mesh geometry={nodes.pSphere13.geometry} material={materials.Black} />
        <mesh geometry={nodes.pSphere14.geometry} material={materials.Black} />
        <mesh geometry={nodes.pSphere15.geometry} material={materials.Black} />
        <mesh geometry={nodes.pSphere16.geometry} material={materials.Black} />
        <mesh geometry={nodes.pSphere17.geometry} material={materials.Black} />
        <mesh geometry={nodes.pSphere18.geometry} material={materials.Black} />
        <mesh geometry={nodes.pSphere19.geometry} material={materials.Black} />
        <mesh geometry={nodes.pSphere20.geometry} material={materials.Black} />
        <mesh geometry={nodes.pSphere21.geometry} material={materials.Black} />
        <mesh geometry={nodes.pSphere22.geometry} material={materials.Black} />
        <mesh geometry={nodes.pSphere23.geometry} material={materials.Black} />
        <mesh geometry={nodes.pSphere25.geometry} material={materials.Black} />
        <mesh geometry={nodes.pSphere26.geometry} material={materials.Black} />
        <mesh geometry={nodes.Mesh106.geometry} material={materials.Body01} />
        <mesh geometry={nodes.Mesh106_1.geometry} material={materials['RobotHEad:blinn1']} />
        <mesh geometry={nodes.Mesh026.geometry} material={materials.Body01} />
        <mesh geometry={nodes.Mesh026_1.geometry} material={materials['RobotHEad:blinn1']} />
        <mesh geometry={nodes.pSphere29.geometry} material={materials.Black} />
        <mesh geometry={nodes.pSphere30.geometry} material={materials.Black} />
        <mesh geometry={nodes.pSphere31.geometry} material={materials.Black} />
        <mesh geometry={nodes.pSphere32.geometry} material={materials.Black} />
        <mesh geometry={nodes.pSphere33.geometry} material={materials.Black} />
        <mesh geometry={nodes.pSphere34.geometry} material={materials.Black} />
        <mesh geometry={nodes.pSphere35.geometry} material={materials.Black} />
        <mesh geometry={nodes.pSphere36.geometry} material={materials.Black} />
        <mesh geometry={nodes.pSphere37.geometry} material={materials.Black} />
        <mesh geometry={nodes.pSphere38.geometry} material={materials.Black} />
        <mesh geometry={nodes.pSphere39.geometry} material={materials.Black} />
        <mesh geometry={nodes.pSphere40.geometry} material={materials.Black} />
        <mesh geometry={nodes.pSphere7.geometry} material={materials.Black} />
        <mesh geometry={nodes.Mesh105.geometry} material={materials.Body01} />
        <mesh geometry={nodes.Mesh105_1.geometry} material={materials['RobotHEad:blinn1']} />
        <mesh geometry={nodes.pSphere9.geometry} material={materials.Black} />
        <mesh geometry={nodes.Mesh069.geometry} material={materials['RobotHEad:mia_material_x2']} />
        <mesh geometry={nodes.Mesh069_1.geometry} material={materials['RobotHEad:blinn1']} />
        <mesh geometry={nodes.Mesh069_2.geometry} material={materials['RobotHEad:mia_material_x1']} />
        <mesh geometry={nodes.RobotHEadpolySurface17.geometry} material={materials['RobotHEad:blinn1']} />
      </group>
    </group>
  )
}

useGLTF.preload('/Robot02glb.glb')
