/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: 3DDisco (https://sketchfab.com/3DDisco)
license: SKETCHFAB Standard (https://sketchfab.com/licenses)
source: https://sketchfab.com/3d-models/animated-hologram-planet-earth-sci-fi-3d-model-9364150ddca744c38256b7fa3c3cc8f9
title: Animated Hologram Planet Earth Sci-Fi 3D Model
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/scene1.glb");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    Object.keys(actions).forEach((key) => {
      actions[key].play();
    });
  }, []);

  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group rotation={[-Math.PI / 1, 0, 0]}>
          <group>
            <group rotation={[Math.PI / 1, 0, 0]} scale={1.1}>
              <group>
                <group>
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <group />
                  <pointLight position={[5, 5, 0]} intensity={3} />
                  <skinnedMesh
                    material-color={"#0AFEFC"}
                    scale={2}
                    geometry={nodes.Object_7.geometry}
                    material={materials.EarthHologram}
                    skeleton={nodes.Object_7.skeleton}
                  />
                  <skinnedMesh
                    material-color={"#047978"}
                    scale={0.25}
                    geometry={nodes.Object_8.geometry}
                    material={materials.Clouds}
                    skeleton={nodes.Object_8.skeleton}
                  />
                  {/* <skinnedMesh scale={4} geometry={nodes.Object_7.geometry} material={materials.EarthHologram} skeleton={nodes.Object_7.skeleton} />
                  <skinnedMesh scale={0.25} geometry={nodes.Object_8.geometry} material={materials.Clouds} skeleton={nodes.Object_8.skeleton} /> */}
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/scene1.glb");
